#!/bin/bash
cd /etc/ansible/backups/

## Remove NTP Clock Period config line
sed -i '/ntp clock-period/d' /etc/ansible/backups/*.cfg

## Remove Current configuration size
sed -i '/Current configuration/d' /etc/ansible/backups/*.cfg
