- hosts: fortigate
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
   - name: Add Edge VDOM firewall Address Object.
     fortios_firewall_address:
       state: present
       vdom: Edge
       firewall_address:
         name: "User_Workstation"
         type: "ipmask"
         subnet: "10.0.0.2/32"
   - name: Add ISFW VDOM firewall Address Object.
     fortios_firewall_address:
       state: present
       vdom: ISFW
       firewall_address:
         name: "User_Workstation"
         type: "ipmask"
         subnet: "10.0.0.2/32"
