#!/bin/bash
cd /etc/ansible/backups/

## Get current timestamp
current_time=$(date)

## Add new files to GIT repo and commit the changes
git add *
git commit -a -m "Newly detected config changes at $current_time"
